### ISSUE TITLE
Error: Cannot find module '../component' @ app/index.js:88:42

### ISSUE THREAD

**Issue by Myrlin1** [AJIXuMuK/generator-vuespfx#10]
After

> npm i -g generator-vuespfx

Then:

> yo vuespfx

Either selection of "Sharepoint Online," or "Sharepoint 2016 and later; includes Sharepoint Online" Throws the following error.

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '../component'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at prompt.then (C:\Users\jeremy.albright\AppData\Roaming\npm\node_modules\generator-vuespfx\app\index.js:88:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\jeremy.albright\AppData\Roaming\npm\node_modules\generator-vuespfx\node_modules\yeoman-generator\lib\index.js:406:18)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

Fixed by cloning the git repository into the global npm node_modules\generator-vuespfx directory,

Let me know if you need any additional details.

**Comment by Myrlin1** [comment]
All is well

**Comment by AJIXuMuK** [comment]
Great! Thanks!
